matrix:
  include:
    - language: node_js
      node_js:
        - 12.18.2
      script:
        - npm install
        - npm install nodemon
        - nodemon
        - npm install newman
        - newman run AutomatedDemo3.postman_collection.json