matrix:
  include:
  - language: node_js
    node_js:
    - 12.18.2
    script:
    - cd STAT-server
    - npm install
    - ng test --headless
    #- npm install nodemon
    #- nodemon
    #- npm test