matrix:
  include:
    - language: ruby
      rvm:
        - 2.6.6
        - truffleruby
      before_install:
        - openssl aes-256-cbc -K $encrypted_2b18cd2778ba_key -iv $encrypted_2b18cd2778ba_iv -in config.json.enc -out STAT-server/config/config.json -d
    - language: node_js
      node_js:
        - 12.18.2
      script:
        - npm install
        - nodemon