matrix:
  include:
  - language: node_js
    node_js:
    - 12.18.2
    script:
    - cd STAT
    - npm install
    - npm rebuild
    - ng test --browsers ChromeHeadless --no-sandbox
    - echo "Finished test"
  branches:
    only:
      - master
      - /^(?i:app)-.*$/