language: ruby
rvm:
- 2.6.6
- truffleruby
nvm:
- 12.18.2
before_install:
- openssl aes-256-cbc -K $encrypted_b46af4c0cf9c_key -iv $encrypted_b46af4c0cf9c_iv
  -in STAT-server/config/config.json.enc -out STAT-server/config/config.json -d
jobs:
  include:
  - stage: server build
    node_js: '7'
    script:
    - npm install
    - nodemon
