matrix:
  include:
  - language: node_js
    node_js:
    - 12.18.2
    script:
    - cd STAT
    - npm install
    - ng test --no-watch --browsers ChromeHeadless
    - echo "Finished test"
  branches:
    only:
      - master
      - /^(?i:app)-.*$/