matrix:
  include:
  - language: node_js
    node_js:
    - 12.18.2
    script:
    - cd STAT-server
    - npm install
    - nodemon
    - npm test
  branches:
    only:
      - master
      - /^(?i:server)-.*$/