name: angular
on: 
    push:
        branches: [ master, 'app-*' ]

jobs:
  angular-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: STAT
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: npm install -g @angular/cli
    - run: ng serve