name: CI
on:
  push:
    branches: [ testing-github-secrets ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: STAT-server
    steps:
      - name: "Server start"
        run:
          npm install
          npm install nodemon
          cd STAT-server
          nodemon
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRETS }}
