name: CI
on:
  push:
    branches: [ testing-github-secrets ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: STAT-server
    steps:
      - uses:
          actions/checkout@v2
          actions/setup-node@v1
      - name: "Server start"
        with:
          node-version: 12.x
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRETS }}
        run:
          npm install
          npm install nodemon
          nodemon
