name: CI
on:
  push:
    branches: [ testing-github-secrets ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      working-directory: ./STAT-server
    steps:
    - name: "Change directory"
      run: npm install nodemon
    - name: "Start server"
      run: nodemon
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}