name: CI
on:
  push:
    branches: [ testing-github-secrets ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Server start"
        run:
          npm install nodemon
          nodemon
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}