name: CI
on:
  push:
    branches: [ testing-github-secrets ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./STAT-server
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: "Install nodemon"
      run:
        npm install
        npm install nodemon
    - name: "Start server"
      run: nodemon
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}